name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-15 # Apple Silicon Runner

    env:
      DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"

    - name: Verify Environment
      run: |
        sw_vers
        xcodebuild -version
        swift --version

    - name: Check Code Formatting
      run: make format-check

    - name: Run SwiftLint
      run: make lint

    - name: Build
      run: make build

    - name: Run Tests
      run: make test

